# Generated by Django 4.2 on 2023-04-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="movie", table="movies",),
    ]
