# Generated by Django 4.2 on 2023-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0002_alter_movie_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
