# Generated by Django 4.2 on 2023-04-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0004_director_movie_director"),
    ]

    operations = [
        migrations.AlterModelTable(name="director", table="directors",),
    ]
